# fly.toml file generated for swl-rplist on 2022-08-28T21:01:49+02:00

app = "swl-rplist"
kill_signal = "SIGINT"
kill_timeout = 5
swap_size_mb = 512
processes = []

[env]
  JAVA_OPTS = "-XX:+UseContainerSupport -Xmx50M -Xms40M -Xss256k -XX:MaxMetaspaceSize=100M -XX:+UnlockDiagnosticVMOptions -XX:+TieredCompilation -XX:TieredStopAtLevel=1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
